spring:
  output:
    ansi:
      enabled: always
  quartz:
    scheduler-name: QuartzScheduler
    job-store-type: memory
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5

#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://op-infradb-04.korea.ncsoft.corp:62224;DatabaseName=JMQuartzTest;SelectMethod=cursor
#    username: smiledev
#    password: roqkf12#
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate.ddl-auto: update
#  quartz:
#    job-store-type: jdbc
#    jdbc:
#      initialize-schema: always
#    properties:
#      org:
#        quartz:
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            dataSource: quartzDataSource
#            tablePrefix: QRTZ_
#          scheduler:
#            instanceName: quartz-jm-app
#            instanceId: AUTO