spring:
  output:
    ansi:
      enabled: always
#  quartz:
#    scheduler-name: QuartzScheduler
#    job-store-type: memory
#    properties:
#      org:
#        quartz:
#          threadPool:
#            threadCount: 5
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://op-infradb-04.korea.ncsoft.corp:62224;DatabaseName=JMQuartzTest;SelectMethod=cursor
    username: ENC(3js+1Wk9lhmOv2pe8AstdI26268BLT3g)
    password: ENC(B70agaV/1dFu9gqlHdNAHSeD/3/5htZ4)
  jpa:
    open-in-view: false
    show-sql: true
    hibernate.ddl-auto: none
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
          scheduler:
            instanceName: quartz-jm-app
            instanceId: AUTO
jasypt:
  encryptor:
    bean: jasyptStringEncryptor