spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://op-infradb-04.korea.ncsoft.corp:62224;DatabaseName=JMQuartzTest;SelectMethod=cursor
    username: ENC(3js+1Wk9lhmOv2pe8AstdI26268BLT3g)
    password: ENC(B70agaV/1dFu9gqlHdNAHSeD/3/5htZ4)
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialec
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      open-in-view: false
      ddl-auto: update
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
          scheduler:
            instanceName: quartz-jm-app
            instanceId: AUTO
          plugin:
            shutdownhook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: TRUE
#          threadPool:
#            threadCount: 1
#            triggerHistory:
#              class: org.quartz.plugins.history.LoggingTriggerHistoryPlugin
#            jobHistory:
#              class: org.quartz.plugins.history.LoggingJobHistoryPlugin

jasypt:
  encryptor:
    bean: jasyptStringEncryptor